# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DofLog_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 182)
        MainWindow.setMinimumSize(QtCore.QSize(363, 182))
        MainWindow.setMaximumSize(QtCore.QSize(363, 182))
        icon = QtGui.QIcon.fromTheme("icon.ico")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.nameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLE.setMinimumSize(QtCore.QSize(153, 0))
        self.nameLE.setMaximumSize(QtCore.QSize(153, 16777215))
        self.nameLE.setObjectName("nameLE")
        self.gridLayout.addWidget(self.nameLE, 0, 1, 1, 1)
        self.passwordLbl = QtWidgets.QLabel(self.centralwidget)
        self.passwordLbl.setMaximumSize(QtCore.QSize(97, 16777215))
        self.passwordLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLbl.setObjectName("passwordLbl")
        self.gridLayout.addWidget(self.passwordLbl, 2, 0, 1, 1)
        self.connectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectBtn.setMinimumSize(QtCore.QSize(0, 75))
        self.connectBtn.setObjectName("connectBtn")
        self.gridLayout.addWidget(self.connectBtn, 4, 2, 1, 1)
        self.organiserBtn = QtWidgets.QPushButton(self.centralwidget)
        self.organiserBtn.setObjectName("organiserBtn")
        self.gridLayout.addWidget(self.organiserBtn, 2, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.upBtn = QtWidgets.QPushButton(self.centralwidget)
        self.upBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.upBtn.setObjectName("upBtn")
        self.gridLayout_3.addWidget(self.upBtn, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.stayLogCB = QtWidgets.QCheckBox(self.centralwidget)
        self.stayLogCB.setObjectName("stayLogCB")
        self.gridLayout_3.addWidget(self.stayLogCB, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.downBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.downBtn.setObjectName("downBtn")
        self.gridLayout_3.addWidget(self.downBtn, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.addBtn.setObjectName("addBtn")
        self.gridLayout.addWidget(self.addBtn, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.passwordLE = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLE.setMinimumSize(QtCore.QSize(153, 0))
        self.passwordLE.setMaximumSize(QtCore.QSize(153, 16777215))
        self.passwordLE.setFrame(True)
        self.passwordLE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLE.setObjectName("passwordLE")
        self.gridLayout.addWidget(self.passwordLE, 2, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(153, 75))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 4, 1, 1, 1)
        self.usernameLbl = QtWidgets.QLabel(self.centralwidget)
        self.usernameLbl.setMaximumSize(QtCore.QSize(97, 16777215))
        self.usernameLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usernameLbl.setObjectName("usernameLbl")
        self.gridLayout.addWidget(self.usernameLbl, 1, 0, 1, 1)
        self.nameLbl = QtWidgets.QLabel(self.centralwidget)
        self.nameLbl.setMaximumSize(QtCore.QSize(97, 16777215))
        self.nameLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLbl.setObjectName("nameLbl")
        self.gridLayout.addWidget(self.nameLbl, 0, 0, 1, 1)
        self.usernameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameLE.setMinimumSize(QtCore.QSize(153, 0))
        self.usernameLE.setMaximumSize(QtCore.QSize(153, 16777215))
        self.usernameLE.setObjectName("usernameLE")
        self.gridLayout.addWidget(self.usernameLE, 1, 1, 1, 1)
        self.deleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.deleteBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.deleteBtn.setObjectName("deleteBtn")
        self.gridLayout.addWidget(self.deleteBtn, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.addBtn.clicked.connect(self.nameLE.clear)
        self.addBtn.clicked.connect(self.usernameLE.clear)
        self.addBtn.clicked.connect(self.passwordLE.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nameLE, self.usernameLE)
        MainWindow.setTabOrder(self.usernameLE, self.passwordLE)
        MainWindow.setTabOrder(self.passwordLE, self.listWidget)
        MainWindow.setTabOrder(self.listWidget, self.addBtn)
        MainWindow.setTabOrder(self.addBtn, self.connectBtn)
        MainWindow.setTabOrder(self.connectBtn, self.organiserBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "- 1.15.26"))
        self.passwordLbl.setText(_translate("MainWindow", "Mot de Passe :"))
        self.connectBtn.setToolTip(_translate("MainWindow", "Connecte le/les compte(s) sélectionné(s)"))
        self.connectBtn.setText(_translate("MainWindow", "Connecter !"))
        self.organiserBtn.setText(_translate("MainWindow", "Organiser (nAiO)"))
        self.upBtn.setText(_translate("MainWindow", "/\\"))
        self.upBtn.setToolTip(_translate("MainWindow", "Monte le compte sélectionné dans la liste"))
        self.stayLogCB.setToolTip(_translate("MainWindow", "Reste connecté à Ankama Launcher après la connexion à Dofus"))
        self.stayLogCB.setText(_translate("MainWindow", "Rester co"))
        self.downBtn.setText(_translate("MainWindow", "\\/"))
        self.downBtn.setToolTip(_translate("MainWindow", "Descend le compte sélectionné dans la liste"))
        self.addBtn.setText(_translate("MainWindow", "Ajouter"))
        self.usernameLbl.setText(_translate("MainWindow", "Nom de compte :"))
        self.nameLbl.setText(_translate("MainWindow", "Nom du raccourci :"))
        self.deleteBtn.setToolTip(_translate("MainWindow", "Supprime le compte sélectionné"))
        self.deleteBtn.setText(_translate("MainWindow", "Supprimer"))
